stages:
  - test
  - deploy

cache:
  paths:
  - vendor/

deploy:
  stage: deploy
  script:
    - apk add curl
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=${CI_COMMIT_TAG} "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/composer"'
  environment: production
  only:
    - tags

